import{a as w,S as v,i as n}from"./assets/vendor-CNqCr-V-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const q="https://pixabay.com/api/",S="53401349-bf79c90e9252dafda11b7b71c";async function f(r,o=1){const e={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await w.get(q,{params:e})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),R=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const o=r.map(e=>`
    <a class="gallery-item" href="${e.largeImageURL}">
      <div class="photo-card">
        <img src="${e.webformatURL}" alt="${e.tags}" />

        <div class="info">
          <p class="info-item"><b>Likes</b> ${e.likes}</p>
          <p class="info-item"><b>Views</b> ${e.views}</p>
          <p class="info-item"><b>Comments</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
        </div>
      </div>
    </a>
  `).join("");p.insertAdjacentHTML("beforeend",o),R.refresh()}function B(){p.innerHTML=""}function y(){m.classList.add("show")}function b(){m.classList.remove("show")}function L(){h.classList.add("show")}function l(){h.classList.remove("show")}const M=document.querySelector(".form"),$=document.querySelector(".load-more");let d="",a=1,u=0;M.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(!o){n.error({message:"Please enter a search query!",position:"topRight"});return}d=o,a=1,B(),l(),y();try{const e=await f(d,a);if(u=e.totalHits,e.hits.length===0){n.warning({message:"No images found. Try another query!",position:"topRight"});return}g(e.hits),a*15<u&&L()}catch{n.error({message:"Something went wrong. Try again later!",position:"topRight"})}finally{b()}});$.addEventListener("click",async()=>{a+=1,y(),l();try{const r=await f(d,a);if(g(r.hits),r.hits.length>0){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}const o=Math.ceil(u/15);a>=o?(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{n.error({message:"Error loading more images.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
